### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
same as reusify :)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Damn it, I commited unfinished work for the badges:

you should cherry-pick https://github.com/AdrieanKhisbe/fastseries/commit/ae22c160a1521588e3ffa97f9b3d9b41358468e9
to fix them.

(tell me if you prefer a PR)

sorry about this @mcollina  :/

**Comment by mcollina** [comment]
I'd prefer a PR.

Please do not cache node_modules. There are some issues with native addons, npm versions and the like.

**Comment by AdrieanKhisbe** [comment]
okey, I'll fix that as well

**Comment by mcollina** [comment]
No worries, I've done that everywhere. Also the after_script was wrong almost everywhere.

**Comment by AdrieanKhisbe** [comment]
Me <- :facepunch: 

I copied the wrong travis template. (In wich was using coveralls rather than coverage).
Ooops

**Pull request merged**
